set_property IOSTANDARD LVCMOS18 [get_ports {switch[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports rst]
set_property IOSTANDARD LVDS [get_ports sys_clk_p]
set_property IOSTANDARD LVDS [get_ports sys_clk_n]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets w_clk]

set_property PACKAGE_PIN AV30 [get_ports {switch[0]}]
set_property PACKAGE_PIN AY33 [get_ports {switch[1]}]
set_property PACKAGE_PIN BA31 [get_ports {switch[2]}]
set_property PACKAGE_PIN BA32 [get_ports {switch[3]}]
set_property PACKAGE_PIN AW30 [get_ports {switch[4]}]
set_property PACKAGE_PIN AY30 [get_ports {switch[5]}]
set_property PACKAGE_PIN BA30 [get_ports {switch[6]}]
set_property PACKAGE_PIN BB31 [get_ports {switch[7]}]
set_property PACKAGE_PIN AV40 [get_ports rst]
set_property PACKAGE_PIN E19 [get_ports sys_clk_p]
set_property PACKAGE_PIN E18 [get_ports sys_clk_n]

set_property IOSTANDARD LVCMOS18 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]

set_property PACKAGE_PIN AU39 [get_ports {led[7]}]
set_property PACKAGE_PIN AP42 [get_ports {led[6]}]
set_property PACKAGE_PIN AP41 [get_ports {led[5]}]
set_property PACKAGE_PIN AR35 [get_ports {led[4]}]
set_property PACKAGE_PIN AT37 [get_ports {led[3]}]
set_property PACKAGE_PIN AR37 [get_ports {led[2]}]
set_property PACKAGE_PIN AN39 [get_ports {led[1]}]
set_property PACKAGE_PIN AM39 [get_ports {led[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports enable]
set_property PACKAGE_PIN AP40 [get_ports enable]